server:
  port: 8080

spring:
  application:
    name: ms-technology
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/technology_db?currentSchema=ms_technology
    username: postgres
    password: 1297
  flyway:
    url: jdbc:postgresql://localhost:5432/technology_db
    user: postgres
    password: 1297
    locations: classpath:db/migration
    schemas: ms_technology
    default-schema: ms_technology

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html